baseURL = "https://carte.anguanadelvin.com/"
languageCode = "en-us"
defaultContentLanguage = "it"
title = "Anguana del Vin"
description = ""
theme = "menu"
copyright = "Copyright &copy; 2020"


[params]
home = "Home"
logo = "images/logo.png"
logoShort = "images/.png"


# contact info
phone = "+39 0435 420 440"
email = "info@monacoscporthotel.com"
location = "Santo Stefano di Cadore (BL), Italia"


[languages.en]
weight = 2
languageName = "English"
contentDir = "content/en"

[[languages.en.menu.main]]
url    = "/sparkling"
name   = "Sparkling wines"
weight = 2

[[languages.en.menu.main]]
url    = "/red"
name   = "Red wines"
weight = 3

[[languages.en.menu.main]]
url    = "/white"
name   = "White wines"
weight = 4

[languages.it]
weight = 0
languageName = "Italiano"
contentDir = "content/it"

[[languages.it.menu.main]]
url    = "/sparkling"
name   = "Spumanti"
weight = 2

[[languages.it.menu.main]]
url    = "/red"
name   = "Vini rossi"
weight = 3

[[languages.it.menu.main]]
url    = "/white"
name   = "Vini bianchi"
weight = 4

[[languages.it.menu.main]]
url    = "/sweet"
name   = "Vini dolci"
weight = 5
